name: Test Project from Github
description: Test Project from Github.
company: unknown

devices:
  SoM From Github:
    category: SoMs
    description: Stub System on Module

  Stub Device From Github:
    contains:
      - som_from_github
    category: Complex devices
